### PR TITLE
Settings and updates for the Python editor

### PR DESCRIPTION
**Pull request by ntoll**
This change adds configuration / settings for a Python editor (as described here: https://github.com/bbc/microbit-extras/issues/1059).

Creating the PR now so we have a place to discuss things specific to configuration. There's already an editor deployed at the specified endpoint (although it's password protected so not public).

### CODE REVIEW

**Comment by ntoll** [comment]
@msftclas open the pod bay door...

:-)

**Comment by mmoskal** [comment]
I'm afraid I can't do that Dave.

**Comment by mmoskal** [comment]
(and seriously we're waiting for BBC with this one)

**Comment by ntoll** [comment]
@mmoskal :-)

I quite understand wrt the BBC. I'm in touch with them in order to fathom what the blocker is - it's certainly not us and it's not you folks, so what on earth could it be..? (I suspect someone needs to be in a meeting and say "make it so"). :-/

**Comment by markjoyce** [comment]
Hi Guys, 

If Microsoft are happy to go ahead. Please proceed.

Apologies for the delay. Thanks.

N.B and this may not be relevant here. Anything Python editor related must only be available in test. (Nicholas, we are locking down and stabilising stage and live for go live purposes - nothing personal :) )

**Comment by ntoll** [comment]
@markjoyce great stuff!

It'd be *really* helpful to have a time-line and requirements list for the process of getting the Python editor into TouchDevelop stage/live.

**Comment by markjoyce** [comment]
Most definitely. I believe Howard and Phil are going to touch base with you on this very soon. It would be great to share our timelines with you and work out how we can integrate the Python editors into these. You should be hearing from them soon. Thanks.

**Comment by aitchgb** [comment]
That's right @markjoyce

**Comment by msprotz** [comment]
@ntoll merged! thanks for the very impressive work. Michał and I will try to figure out how to let you guys re-use the simulator (assuming that's feasible easily) and will get in touch. Let us know if you have any further requests!

**Comment by ntoll** [comment]
@msprotz thank you!

Regarding the simulator... it's a long shot but definitely a good to have. As you correctly surmised, given code and documentation, we need to examine its feasibility with Python.

**Comment by msprotz** [comment]
We'd actually be happy to try out the python editor. Can you use the same username / password as for the main site? We don't know what the current credentials are. Thanks!

**Comment by ntoll** [comment]
I've updated the credentials. If they don't work please give me a kick (they're the ones I use on the test.mb.c.u site).

All feedback greatly appreciated - it works and could probably do with some polishing. 

Enjoy... ;-)

**Comment by aitchgb** [comment]
Thanks Jonathan and Michal -- brilliant!

**Comment by ntoll** [comment]
Just a quick question... what's the ETA of this landing in (I presume) test.microbit.co.uk..?

Have a great weekend! :-)

**Comment by msprotz** [comment]
It's already enabled (via the legal footer). You need to file a separate issue on the other repository and work with @adamslater-tangent so that "create code" lists the new editor

**Pull request merged**
