### PR TITLE
UI & Code Changes

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by msprotz** [comment]
Hi,

Thanks for the pull request! Here's a few requests before I can actually review this.

* Please provide a couple screenshots so that we can easily see what changed
* The diff for `editor.css` is not readable, I suspect you changed the line-endings. Please leave the line-endings as is (git config core.autocrlf false) when committing.

Thanks!

Jonathan

**Comment by wongalvis** [comment]
@msprotz The diff for editor.css is not readable because there are too many lines changed as I indented the lines.

**Comment by msprotz** [comment]
Hi,

After chatting about it, we feel that even though this is a valid contribution, the appearance / fonts / margin is a very subjective thing. We expect to have some help in refreshing the interface soon, so a big cleanup is due. In the meanwhile, we'd rather not change stuff.

Thanks,

Jonathan

**Comment by wongalvis** [comment]
@msprotz Would I be able to participate in the making of new UI?

**Comment by wongalvis** [comment]
@msprotz Could I participate in building the new UI?

**Pull request closed without merging**
